/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.hw01;

import org.apache.commons.cli.*;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Arrays;
import java.util.Scanner;

public class App {

    public static void main(String[] args) throws ParseException, FileNotFoundException {
        Options options = new Options();

        options.addOption("h", false, "prints help/usage message");
        options.addOption("b", true, "processes file instead of standard input");
        options.addOption("o", true, "prints to file instead of standard output");

        CommandLineParser parser = new DefaultParser();
        CommandLine cmd = parser.parse(options, args);

        if(cmd.hasOption("h")){
            System.out.println("""
                                  usage: eval [OPTIONS]
                                  Evaluation of simple mathematical expressions
                                  
                                  -b,--batch <file>    batch file containing expressions to evaluate
                                  -h,--help            print usage message
                                  -o,--output <file>   output file
                                  
                                  Copyright (C) 2022 Grant Madson""");
        }

        if(cmd.hasOption("b")){
            System.out.println("Batch value: " + args[1]);

            }

        if(cmd.hasOption("o")){
            System.out.println("Output value: "+args[1]);
        }
    }
}
